version: '3.3'

services:
    django_gunicorn:
        volumes:
            - static:/static
        env_file:
            - .env
        build:
            context: .
        ports:
            - "8000:8000"
    
    nginx:
        build: ./nginx
        volumes:
            - static:/static
        ports:
            - "80:80"
        depends_on:
            - django_gunicorn
            
    db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - .env.db

volumes:
    static:
    postgres_data:    